databases:
  - name: nfl-geoguessr-db
    plan: free
    databaseName: nfl_geoguessr

services:
  - type: web
    name: nfl-geoguessr
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: nfl-geoguessr-db
          property: connectionString
